<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymEquipmentManagement\GEMBusinessLogic\GEMBusinessLogic.csproj" />
    <ProjectReference Include="..\GymEquipmentManagement\GEMCommon\GEMCommon.csproj" />
    <ProjectReference Include="..\GymEquipmentManagement\GEMDataAccess\GEMDataAccess.csproj" />
  </ItemGroup>

</Project>