<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\GEMBusinessLogic\GEMBusinessLogic.csproj" />
		<ProjectReference Include="..\GEMCommon\GEMCommon.csproj" />
		<ProjectReference Include="..\GEMDataAccess\GEMDataAccess.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="FluentAssertions" Version="8.8.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>
